version: "3.8"
services:
  # server:
  #   build:
  #     context: .
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_URL: postgresql://sopt_user:sopt_password@db/sopt_api
  #     PORT: 4000
  #   depends_on:
  #     - db
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
